---
media_quadlet_auto_update: true
media_operation: update # update | deploy
media_project_dir: /var/lib/media
media_data_dir: "{{ media_project_dir }}/data"
media_mount_root: /var/mnt/external

media_quadlet_options_main:
  - |
    [Container]
    AutoUpdate=registry
  - |
    [Unit]
    Wants=network-online.target
    After=network-online.target
    RequiresMountsFor={{ media_mount_root }}
  - |
    [Service]
    Restart=always
    RestartSec=5
  - |
    [Install]
    WantedBy=default.target
