- name: Assert supported OS
  ansible.builtin.assert:
    that: >-
      ansible_facts["os_family"] == "Debian"
      or ansible_facts["distribution"] == "openSUSE MicroOS"
      or ansible_facts["os_family"] == "Alpine"
    fail_msg: "Unsupported OS: {{ ansible_facts['distribution'] }} ({{ ansible_facts['os_family'] }})"

- name: Run Debian package tasks
  ansible.builtin.include_tasks: debian.yaml
  when: ansible_facts["os_family"] == "Debian"

- name: Run MicroOS package tasks
  ansible.builtin.include_tasks: microos.yaml
  when: ansible_facts["distribution"] == "openSUSE MicroOS"

- name: Run Alpine package tasks
  ansible.builtin.include_tasks: alpine.yaml
  when: ansible_facts["os_family"] == "Alpine"
