---
- name: Create or update Gluetun Quadlet definition
  containers.podman.podman_container:
    name: "{{ item.name }}"
    image: docker.io/qmcgaw/gluetun:latest
    state: quadlet
    quadlet_dir: /etc/containers/systemd
    quadlet_filename: "{{ item.name }}"
    quadlet_file_mode: "0644"
    network: "{{ item.network | default(['host']) }}"
    privileged: true
    capabilities:
      - NET_ADMIN
      - NET_RAW
    device:
      - /dev/net/tun:/dev/net/tun
    volume:
      - "{{ item.config_dir }}:/gluetun:Z"
    env: "{{ item.meta.env }}"
    quadlet_options: "{{ media_quadlet_options_main + (item.quadlet_options_extra | default([])) }}"
  become: true
  notify: Reload systemd daemon
