---
- name: Create or update qBittorrent Quadlet definition
  containers.podman.podman_container:
    name: "{{ item.name }}"
    image: lscr.io/linuxserver/qbittorrent:latest
    state: quadlet
    quadlet_dir: /etc/containers/systemd
    quadlet_filename: "{{ item.name }}"
    quadlet_file_mode: "0644"
    network:
      - container:gluetun
    volume:
      - "{{ item.config_dir }}:/config:Z"
      - "{{ media_mount_root }}/torrents:/downloads"
    env: "{{ item.meta.env }}"
    quadlet_options: "{{ media_quadlet_options_main + (item.quadlet_options_extra | default([])) }}"
  become: true
  notify: Reload systemd daemon
