---
- name: Reload systemd user daemon
  ansible.builtin.systemd_service:
    scope: user
    daemon_reload: true
  become: true
  become_user: "{{ ansible_user }}"
  environment:
    XDG_RUNTIME_DIR: "{{ infra_quadlet_runtime_dir }}"

- name: Reload systemd daemon
  ansible.builtin.systemd_service:
    scope: system
    daemon_reload: true
  become: true

- name: Enable podman auto-update timer (user scope)
  ansible.builtin.systemd_service:
    name: podman-auto-update.timer
    enabled: true
    state: started
    scope: user
  become: true
  become_user: "{{ ansible_user }}"
  environment:
    XDG_RUNTIME_DIR: "{{ infra_quadlet_runtime_dir }}"
  failed_when: false

- name: Enable podman auto-update timer (system scope)
  ansible.builtin.systemd_service:
    name: podman-auto-update.timer
    enabled: true
    state: started
    scope: system
  become: true
  failed_when: false
