---
# Container-specific variables
media_containers:
  - name: plex
    task: containers/plex.yaml
    config_dir: "{{ media_data_dir }}/plex"
    meta:
      env: {}
      force_reprovision: false
      x_plex_token: "{{ media_plex_x_plex_token }}"
      preferences:
        MetricsEpoch: "1"
        GlobalMusicVideoPathMigrated: "1"
        AcceptedEULA: "1"
        PublishServerOnPlexOnlineKey: "0"
        DvrIncrementalEpgLoader: "0"
        PubSubServerPing: "133"
        CertificateVersion: "3"
        LanguageInCloud: "1"
        PubSubServer: "139.162.134.185"
        PubSubServerRegion: "fra"
        FSEventLibraryUpdatesEnabled: "1"
        ScheduledLibraryUpdateInterval: "43200"
        ScheduledLibraryUpdatesEnabled: "1"
        IPNetworkType: "v4only"
        RelayEnabled: "0"
        LibraryVideoPlayedThreshold: "85"
        sendCrashReports: "0"
        LogVerbose: "1"
        TranscoderQuality: "1"
        TranscoderThrottleBuffer: "900"
        OptimizerTranscodeCountLimit: "2"
        _CPU-TranscodeCountLimit: "2"
        DownloadsTempDirectory: ""
        TranscoderTempDirectory: ""
        LanNetworksBandwidth: "192.168.1.0/24,192.168.40.0/24,192.168.20.0/24,192.168.10.0/24"
        allowedNetworks: "192.168.40.3"
  - name: radarr
    task: containers/radarr.yaml
    config_dir: "{{ media_data_dir }}/radarr"
    network:
      - media-network
    ports:
      - "7878:7878"
    meta:
      env:
        TZ: "Europe/Warsaw"
  - name: sonarr
    task: containers/sonarr.yaml
    config_dir: "{{ media_data_dir }}/sonarr"
    network:
      - media-network
    ports:
      - "8989:8989"
    meta:
      env:
        TZ: "Europe/Warsaw"
  - name: prowlarr
    task: containers/prowlarr.yaml
    config_dir: "{{ media_data_dir }}/prowlarr"
    network:
      - media-network
    ports:
      - "9696:9696"
    meta:
      env:
        TZ: "Europe/Warsaw"
  - name: delugevpn
    task: containers/delugevpn.yaml
    config_dir: "{{ media_data_dir }}/delugevpn"
    system_service: true
    network:
      - media-network
    ports:
      - "8112:8112"
      - "58946:58946"
    quadlet_options_extra:
      - |
        [Service]
        TimeoutStartSec=600
    meta:
      env:
        VPN_ENABLED: "yes"
        VPN_CLIENT: "wireguard"
        VPN_PROV: "custom"
        LAN_NETWORK: "{{ media_delugevpn_lan_network }}"
        ENABLE_PRIVOXY: "no"
        PUID: "{{ media_quadlet_uid }}"
        PGID: "{{ media_quadlet_gid }}"
        UMASK: "000"
        DEBUG: "false"
        TZ: "Europe/Warsaw"
        DELUGE_DAEMON_LOG_LEVEL: "info"
        DELUGE_WEB_LOG_LEVEL: "info"
        DELUGE_ENABLE_WEBUI_PASSWORD: "yes"
  - name: bazarr
    task: containers/bazarr.yaml
    config_dir: "{{ media_data_dir }}/bazarr"
    network:
      - media-network
    ports:
      - "6767:6767"
    quadlet_options_extra:
      - |
        [Service]
        TimeoutStartSec=300
    meta:
      env:
        TZ: Europe/Warsaw

# containers to deploy/update (empty = all):
media_containers_selected: []
