---
- name: Media
  hosts: media
  become: true
  roles:
    - role: packages
      tags: packages
    - role: media
      tags: media

- name: Infra
  hosts: infra
  become: true
  roles:
    - role: packages
      tags: packages
    - role: infra
      tags: infra

- name: Unifi
  hosts: unifi
  become: true
  roles:
    - role: unifi
      tags: unifi
